name: ccpd_app_stacked
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  supabase_flutter: ^2.5.0
  file_picker: ^8.0.0+1
  intl_phone_field2: ^3.3.4
  intl: ^0.19.0
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  loading_indicator: ^3.1.1
  onesignal_flutter: ^5.1.6
  csv: ^5.1.1
  percent_indicator: ^4.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # assets:
    # - assets/images/
   

